export interface Post {
    id: number;
    category: string;
    title: string;
    content: string;
    author: string;
    time: string;
    likes: number;
    comments: number;
    views?: number;
    isHot?: boolean;
}

export const CATEGORIES = [
    { id: 'all', name: '전체' },
    { id: 'talk', name: '선수 소통방' },
    { id: 'region', name: '지역방' },
    { id: 'ssul', name: '선수 썰' },
    { id: 'tip', name: '선수 팁' },
    { id: 'market', name: '중고거래' },
    { id: 'legal', name: '무료법률상담' },
    { id: 'lounge', name: '프리미엄 라운지' },
] as const;

export type CategoryId = typeof CATEGORIES[number]['id'];

const RAW_MOCK_POSTS: Post[] = [
    // ── 프리미엄 라운지 ──────────────────────────────────────────
    {
        id: 40,
        category: '프리미엄 라운지',
        title: '형님들 진상 손님 블랙리스트 공유합니다 (필독)',
        content: '요즘 이상한 손님들이 너무 많네요. 직접 겪은 케이스 정리해서 공유합니다. 다들 조심하세요! 특히 과도한 신체접촉 요구하거나 개인 연락처 요구하는 손님은 바로 매니저 부르세요.',
        author: '정보통형님',
        time: '5분 전',
        likes: 48,
        comments: 6,
        isHot: true,
    },
    {
        id: 42,
        category: '프리미엄 라운지',
        title: '선수 시작 3일차 수입 공개합니다',
        content: '걱정 많이 했는데 생각보다 잘 벌리네요. 고민하는 형님들 위해 용기 내서 올립니다! 첫날엔 좀 헤맸는데 둘째날부터 요령이 생기니까 수입이 확 늘었어요. 텐카페 vs 호스트바 차이점도 알려드릴게요.',
        author: '뉴비선수',
        time: '20분 전',
        likes: 52,
        comments: 8,
        isHot: true,
    },
    {
        id: 82,
        category: '프리미엄 라운지',
        title: '20대에 1억 모으기 달성 인증 — 선수 3년 후기',
        content: '잠 안 자고 투잡 뛰고 재테크 공부해서 드디어 앞자리 바꿨어요! 처음엔 막막했는데 지출 관리 + 적금 + 소액 투자 병행하니까 눈에 보이더라고요. 비결 궁금한 형님들 댓글 달아주세요.',
        author: '자산가형님',
        time: '3시간 전',
        likes: 55,
        comments: 19,
        isHot: true,
    },
    {
        id: 88,
        category: '프리미엄 라운지',
        title: '업소 잘 고르는 기준 공유 — 텐카페 vs 호스트바 비교',
        content: '업소 선택이 수입을 결정합니다. 텐카페는 고정 수입이 안정적이고, 호스트바는 지명 수입이 커요. 4년간 경험으로 정리한 선택 기준 공유합니다.',
        author: '4년차선수',
        time: '15시간 전',
        likes: 60,
        comments: 18,
        isHot: true,
    },
    {
        id: 17,
        category: '프리미엄 라운지',
        title: '멘탈 관리 루틴 — 야근 많아도 버티는 법',
        content: '새벽까지 일하다 보면 멘탈이 먼저 나가더라고요. 저는 퇴근 후 30분 산책 + 주 3회 헬스로 버티고 있어요. 형님들만의 루틴 있으면 공유해주세요!',
        author: '건강형님',
        time: '1시간 전',
        likes: 29,
        comments: 5,
    },
    {
        id: 35,
        category: '프리미엄 라운지',
        title: '업소 이직할 때 주의사항 — 계약서 필수 확인 항목',
        content: '이직 3번 해보니까 계약서에서 꼭 봐야 할 항목들이 있더라고요. 지명 수수료율, 주거 지원, 의류비 지원, 퇴직금 조항. 구두 약속은 절대 믿으면 안 됩니다.',
        author: '이직전문가',
        time: '2시간 전',
        likes: 24,
        comments: 7,
        isHot: true,
    },

    // ── 선수 소통방 ──────────────────────────────────────────────
    {
        id: 1,
        category: '선수 소통방',
        title: '오늘 퇴근길 새벽 하늘 진짜 힐링이네요',
        content: '새벽 6시에 퇴근하는데 하늘이 너무 예쁘더라고요. 일하면서 힘든 것도 이런 순간에 충전되는 것 같아요. 형님들도 오늘 고생 많으셨어요!',
        author: '익명선수',
        time: '10분 전',
        likes: 12,
        comments: 2,
    },
    {
        id: 100,
        category: '선수 소통방',
        title: '이번 달 처음으로 지명 수입 300 넘겼어요',
        content: '드디어 목표 달성했습니다! 3개월 만에 해냈네요. 손님 응대 스타일 바꾸고 나서 지명이 크게 늘었어요. 다들 파이팅입니다!',
        author: '목표달성형님',
        time: '30분 전',
        likes: 43,
        comments: 16,
        isHot: true,
    },
    {
        id: 101,
        category: '선수 소통방',
        title: '선수 시작 고민 중인데 현실적으로 어떤가요?',
        content: '일반 알바 하다가 수입 때문에 고민 중이에요. 주위에서 걱정하는 시선도 있고... 형님들 처음 시작할 때 어떠셨어요? 솔직한 후기 부탁드립니다.',
        author: '고민중형님',
        time: '1시간 전',
        likes: 18,
        comments: 14,
    },
    {
        id: 102,
        category: '선수 소통방',
        title: '같이 일할 파트너 구합니다 (강남/홍대 권역)',
        content: '혼자 다니다 보니까 불편한 점이 많더라고요. 정보 공유하고 위급 상황에 도움 주고받을 파트너 구합니다. 비슷한 경력이면 좋겠어요.',
        author: '파트너구함',
        time: '2시간 전',
        likes: 9,
        comments: 3,
    },

    // ── 선수 썰 ──────────────────────────────────────────────────
    {
        id: 50,
        category: '선수 썰',
        title: '오늘 VIP 손님이 갑자기 영어로만 얘기하자고 해서 ㅋㅋ',
        content: '테이블 담당하다가 손님이 갑자기 영어로만 대화하자고 해서 진땀뺐네요 ㅋㅋ 다행히 고등학교 영어가 도움이 됐어요. 결국 팁도 두둑하게 받았습니다.',
        author: '영어선수',
        time: '25분 전',
        likes: 57,
        comments: 15,
        isHot: true,
    },
    {
        id: 51,
        category: '선수 썰',
        title: '진상 손님 응대하다 진짜 웃긴 일 생겼어요 ㅋㅋ',
        content: '술값 계산하면서 카드가 안 된다고 우기는 손님이 계셨는데, 알고 보니 카드를 거꾸로 꽂으셨더라고요 ㅋㅋ 표정 관리하고 도와드렸더니 감사하다며 팁 주고 가셨어요.',
        author: '표정관리형님',
        time: '40분 전',
        likes: 44,
        comments: 12,
        isHot: true,
    },
    {
        id: 52,
        category: '선수 썰',
        title: '어제 일하다 유명 유튜버 마주쳤습니다 (실화)',
        content: '확실히 누군지는 말 못 하지만 구독자 100만 이상인 분이셨어요. 직업 특성상 비밀 유지가 기본이라 내색 안 했는데 퇴장하면서 명함 한 장 주고 가셨네요.',
        author: '비밀유지형님',
        time: '1시간 전',
        likes: 59,
        comments: 22,
        isHot: true,
    },
    {
        id: 80,
        category: '선수 썰',
        title: '첫 출근날 실수 모음 — 3년 지나서야 웃으며 회상',
        content: '첫날 테이블 번호를 헷갈려서 다른 테이블 음료를 가져다드렸어요... 매니저님이 눈치채고 조용히 수습해주셨는데 지금 생각하면 웃기지만 그때는 식은땀이 ㅠ. 신입 시절 썰 있으면 공유해주세요!',
        author: '3년차선수',
        time: '1시간 전',
        likes: 58,
        comments: 21,
        isHot: true,
    },
    {
        id: 6,
        category: '선수 썰',
        title: '형님들 담배 끊는 법 좀 공유해주세요',
        content: '업소 특성상 간접흡연도 많고 스트레스받으면 더 피게 되더라고요. 건강 생각해서 끊어보려는데 쉽지 않네요. 성공한 형님들 방법 공유 부탁드립니다.',
        author: '금연도전',
        time: '4시간 전',
        likes: 9,
        comments: 3,
    },

    // ── 선수 팁 ──────────────────────────────────────────────────
    {
        id: 41,
        category: '선수 팁',
        title: '지명 올리는 팁 — 단골 손님 관리가 핵심이에요',
        content: '신규 손님 유치도 중요하지만 단골 관리가 장기 수입의 핵심이에요. 손님 취향, 기념일, 선호 주류 메모해두면 재방문율이 확 달라집니다. 이 방법으로 3개월 만에 지명 2배 올렸어요.',
        author: '단골관리형님',
        time: '12분 전',
        likes: 38,
        comments: 4,
        isHot: true,
    },
    {
        id: 18,
        category: '선수 팁',
        title: '야간 근무 피로 회복 영양제 추천 (내돈내산)',
        content: '야간 근무 특성상 피로가 누적되는데 홍삼 + 비타민B군 + 마그네슘 조합이 제일 효과적이었습니다. 내돈내산 찐후기예요.',
        author: '건강챙기기',
        time: '45분 전',
        likes: 15,
        comments: 4,
    },
    {
        id: 90,
        category: '선수 팁',
        title: '업소 면접 볼 때 꼭 확인해야 할 것들',
        content: '면접 때 중요한 조건을 못 확인하고 계약하는 경우가 많아요. 지명 수수료율, 정산 주기, 의류비 지원, 주거 지원 여부 — 이 4가지는 반드시 확인하세요.',
        author: '면접전문가',
        time: '30분 전',
        likes: 43,
        comments: 16,
        isHot: true,
    },
    {
        id: 91,
        category: '선수 팁',
        title: '손님이 술 권할 때 음주 조절하는 현실적인 방법',
        content: '음주량 조절 못 하면 건강도 망가지고 다음 날 업무도 힘들어요. 물 전략적으로 활용하기, 술잔 교체 타이밍 잡기, 단골 손님과 신뢰 쌓아서 양해 구하기 — 효과 있었어요.',
        author: '절주형님',
        time: '1시간 전',
        likes: 37,
        comments: 12,
        isHot: true,
    },
    {
        id: 93,
        category: '선수 팁',
        title: '외모 관리 루틴 — 선수 현직들이 실제로 하는 방법',
        content: '야간 근무 후 낮에 헬스 1시간 + 단백질 식단이 기본이 됐어요. 피부 관리는 수분 크림 + 자외선 차단이 전부인데 효과 좋아요. 형님들만의 루틴 공유해주세요!',
        author: '외모관리형님',
        time: '2시간 전',
        likes: 56,
        comments: 31,
        isHot: true,
    },

    // ── 지역방 ──────────────────────────────────────────────────
    {
        id: 83,
        category: '지역방',
        title: '강남 구역 텐카페 분위기 요즘 어때요?',
        content: '강남 쪽으로 이직 고민 중인데 요즘 분위기 어떤지 현직 형님들 의견 궁금합니다. 손님층이나 지명 흐름이 어떤지 공유해주시면 감사하겠습니다.',
        author: '이직고민',
        time: '4시간 전',
        likes: 27,
        comments: 11,
    },
    {
        id: 84,
        category: '지역방',
        title: '홍대/마포 쪽 신규 오픈 업소 정보 아시는 분?',
        content: '홍대 쪽에 새로 오픈한 호스트바 있다고 들었는데 구체적인 정보를 못 찾겠어요. 알고 계신 분 있으면 DM이나 댓글로 알려주세요.',
        author: '홍대형님',
        time: '5시간 전',
        likes: 53,
        comments: 24,
        isHot: true,
    },
    {
        id: 85,
        category: '지역방',
        title: '부산 서면 업소 비교해봤어요 (3군데 면접 후기)',
        content: '서면 주요 업소 3군데 직접 면접 보고 비교해봤습니다. 지명 수수료, 시설, 주거 지원까지 솔직하게 정리했어요. 부산 형님들께 도움이 됐으면 합니다.',
        author: '부산형님',
        time: '6시간 전',
        likes: 46,
        comments: 28,
        isHot: true,
    },

    // ── 중고거래 ─────────────────────────────────────────────────
    {
        id: 92,
        category: '중고거래',
        title: '정장 수트 팝니다 — 105 사이즈, 3회 착용',
        content: '업소 면접용으로 샀는데 체형이 바뀌어서 팔아요. 브랜드: 갤럭시, 105 사이즈. 원가 38만원, 15만원에 팝니다. DM 주세요.',
        author: '정장판매',
        time: '3시간 전',
        likes: 5,
        comments: 8,
    },
];

const RAW_MOCK_COMMENTS = [
    { id: 4001, postId: 40, author: '정보감사', content: '이런 정보 너무 필요했어요! 저장해뒀어요', time: '3분 전' },
    { id: 4002, postId: 40, author: '조심해야지', content: '저도 비슷한 손님 만난 적 있는데 소름이네요', time: '7분 전' },
    { id: 4201, postId: 42, author: '궁금한형님', content: '텐카페 vs 호스트바 차이 더 알려주세요!', time: '5분 전' },
    { id: 4202, postId: 42, author: '나도해볼까', content: '저도 고민 중인데 무섭긴 해요 솔직히', time: '12분 전' },
    { id: 4203, postId: 42, author: '응원해요', content: '멋지다!! 저도 용기 내볼게요', time: '20분 전' },
    { id: 8201, postId: 82, author: '대단해요', content: '진짜 대단하세요! 팁 좀 공유해주세요!!', time: '8분 전' },
    { id: 8202, postId: 82, author: '투잡추천', content: '투잡은 어떤 걸 하셨어요?', time: '18분 전' },
    { id: 8801, postId: 88, author: '궁금해요', content: '텐카페 수수료율 보통 얼마예요?', time: '10분 전' },
    { id: 8802, postId: 88, author: '유용해요', content: '체크리스트 저장해뒀어요 감사합니다', time: '22분 전' },
    { id: 1001, postId: 1, author: '공감', content: '새벽 퇴근길 하늘이 진짜 힐링이죠 ㅠ', time: '8분 전' },
    { id: 10001, postId: 100, author: '축하해요', content: '축하드려요! 어떤 점 바꾸셨어요?', time: '5분 전' },
    { id: 10101, postId: 101, author: '경험자', content: '처음엔 다 걱정하죠. 해보면 생각보다 괜찮아요', time: '10분 전' },
    { id: 5001, postId: 50, author: '영어공부해야겠다', content: '저도 대비해서 영어 공부 시작했어요 ㅋㅋ', time: '10분 전' },
    { id: 5101, postId: 51, author: '표정관리ㅋㅋ', content: '표정 관리가 진짜 프로네요 ㅋㅋ', time: '8분 전' },
    { id: 4101, postId: 41, author: '지명올라갔어요', content: '메모 시작했는데 진짜 효과 있어요!', time: '5분 전' },
    { id: 9001, postId: 90, author: '유용해요', content: '4가지 다음 면접에서 꼭 확인할게요', time: '5분 전' },
    { id: 8301, postId: 83, author: '강남현직', content: '강남 텐카페는 요즘도 괜찮아요. 주말 손님이 특히 많네요', time: '12분 전' },
    { id: 8501, postId: 85, author: '부산형님1', content: '서면 정보 공유 감사해요! 3번 업소 어디예요?', time: '8분 전' },
];

export const MOCK_POSTS = RAW_MOCK_POSTS;
export const MOCK_COMMENTS = RAW_MOCK_COMMENTS;
